"use client"
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './Header';
import Sidebar from './Sidebar';
import { Layout } from 'antd';
import { useRouter } from 'next/navigation';
import { useEffect } from 'react';
import { retrieveFromSessionStorage } from '@/utils/sessionStorage';

const { Content } = Layout;

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();

  useEffect(() => {


    // Parse userData string to object
    const userData = retrieveFromSessionStorage('user');    

    if (!userData) {
      return router.push('/login');
    }

    const { token } = userData;

    // If the token is not available, navigate to the login page
    if (!token) {
      router.push('/login');
    }

  }, []); // Empty dependency array ensures that the effect runs only once after the component mounts

  return (
    <Layout style={{ minHeight: '100vh' }}>
      <Sidebar />
      <Layout className="site-layout">
        <Header />
        <Content style={{ margin: '16px' }}>
          {children}
        </Content>
      </Layout>
    </Layout>
  )
}
